Chipppppppppp/LIME

app/src/main/AndroidManifest.xml
app/src/main/res/values/arrays.xml

xposed_scopeを用いてLINEを適用おすすめアプリになるようにし、設定しやすくなります。![Screenshot_20240119-164542_LSPosed~2.jpg](https://github.com/Chipppppppppp/LIME/assets/83483662/dccafee4-2966-4657-8100-24c8a17a4a96)

おすすめアプリとして設定

---

app/src/main/java/io/github/chipppppppppp/lime/Main.java

#8 のコミットを含んでいるので先にマージしてからマージしていただけたら 🙇‍♂️ 
Before
After

ボトムナビゲーションの位置調整

---

.github/workflows/build.yml

#4 の一部修正です。
一応ドラフトにはしていたはずなのですが...  
これで完了です。

プレフィックスの重複を修正

---

app/src/main/java/io/github/chipppppppppp/lime/Main.java

VOOMボタンをリソース名からリソースＩＤを動的に取得するようにしました
```
LINE_13.21.0\res\layout\app_main_bottom_navigation_bar.xml
```

ボトムナビゲーションのVOOMボタンの取得方法を修正

---

app/src/main/AndroidManifest.xml
app/src/main/java/io/github/chipppppppppp/lime/SettingsActivity.java
app/src/main/res/layout/settings_activity.xml
app/src/main/res/values-ja/strings.xml
app/src/main/res/values/strings.xml

テキストを strings.xml に移行 & 日本語訳の追加

---

.github/workflows/build.yml
app/.gitignore
app/build.gradle
app/src/main/java/io/github/chipppppppppp/lime/Main.java
app/src/main/java/io/github/chipppppppppp/lime/SettingsActivity.java
app/src/main/res/layout/settings_activity.xml
app/src/main/res/values-ja/strings.xml
app/src/main/res/values/strings.xml
build.gradle

https://twitter.com/Chi_p/status/1748585644945785256
Twitter で会話していた内容です。  
ついでに色々修正しました。

自動リリースするファイル名の修正

---

.github/workflows/build.yml

ワークフローの権限を修正

---

app/src/main/java/io/github/chipppppppppp/lime/Main.java

#41 のコメントから。
Prefsの読み込み時だけXSharedPreferencesを使用するように変更しています。
多分動いてます

Use XSharedPreferences when loading prefs

---

.github/ISSUE_TEMPLATE/config.yml

テンプレート内のIssueのみ許可

---

app/build.gradle

minSdk をアップグレード

---

app/build.gradle
app/src/main/java/io/github/chipppppppppp/lime/MainActivity.java
settings.gradle

Upgrade AGP

---

app/src/main/AndroidManifest.xml
app/src/main/java/io/github/chipppppppppp/lime/Main.java
app/src/main/res/values-ja/strings.xml
app/src/main/res/values/strings.xml

Close #73
AlertDialogの`OK`を押したタイミングでLINEアプリを再起動します。

LINEアプリを自動再起動

---

app/src/main/java/io/github/chipppppppppp/lime/Main.java

常時サイレントメッセージを有効化する
LINE バージョン　14.2.0

常時サイレントメッセージにする

---

app/src/main/java/io/github/chipppppppppp/lime/Main.java

Android Studio により追記するよう促されていたのでAndroidXを用いずに追記しました。

Add @NonNull

---

app/src/main/java/io/github/chipppppppppp/lime/LimeOptions.java
app/src/main/java/io/github/chipppppppppp/lime/Main.java
app/src/main/res/values-ja/strings.xml
app/src/main/res/values/strings.xml

hot_deal_content_recycler_view LYPプレミアム会員限定価格お得な商品をお知らせする機能をホームタブに追加する機能を無効化するためのid
---

LYPプレミアム会員限定価格お得な商品をお知らせする機能をホームタブに追加する機能を無効化する機能の追加

---

.github/ISSUE_TEMPLATE/bug_report.yml

Revert "Update bug_report.yml"

---

app/src/main/java/io/github/chipppppppppp/lime/Main.java

ページ読み込み終了すると真っ白になるのを改善
resolve #103"
---

ページ読み込み終了すると真っ白になるのを改善

---

app/src/main/res/value-zh-rTW/strings.xml

---
繁体字中国語の翻訳を追加しました (Translate based from **HolyBear** and  approved from **tony8077616**)

Add Traditional Chinese translate

---

app/build.gradle

---
動作は変わりませんが、パッケージサイズを削減できます。

customtabs をダウングレード

---

.github/workflows/build.yml
app/build.gradle

---
- 使用する action の変更
- Gradle のビルドログを更に細かく出力
- リリース時に一部文章を予め用意

ビルドワークフローを更新

---

gradle/wrapper/gradle-wrapper.properties

---
Gradleをダウンロードする時にハッシュの検証を行います。
これは、`./gradlew wrapper`でも上書きされます。

gradle-wrapper.properties にハッシュ値を追加

---

README.md

README の崩壊を修正

---

.github/ISSUE_TEMPLATE/bug_report.yml
.github/ISSUE_TEMPLATE/config.yml
.github/ISSUE_TEMPLATE/feature_request.yml

---
- テンプレのタイトルに英語表記を追加
- Discussions へのリンクを追加
質問等に活用予定

Issues を修正

---

.github/workflows/build.yml

---
[actions/attest-build-provenance](https://github.com/actions/attest-build-provenance) を追加

Attest を追加

---

gradle/wrapper/gradle-wrapper.properties
gradlew

Gradle を 8.8 に更新

---

.github/ISSUE_TEMPLATE/bug_report.yml
.github/ISSUE_TEMPLATE/feature_request.yml

---
テンプレを一部修正
日本語が解らない場合は無理して日本語に訳さず英語に翻訳させたい

Issue template

---

.github/workflows/build.yml
app/src/main/java/io/github/chipppppppppp/lime/hooks/PreventUnsendMessage.java

アーティファクト名が気に入らなければ修正して頂いても構いません。
---
リリースビルド時に、LSPatch された LINE の APK も同時にアップロードします。
リリース時以外にも Actions から LSPatch の項目にチェックを入れてからビルドすると、アーティファクトにパッチされた LINE の APK が出てきます。

自動 LSPatch 機能を追加

---

app/build.gradle
app/src/main/java/io/github/chipppppppppp/lime/hooks/CheckHookTargetVersion.java

---
versionName だと armeabi-v7a のパッケージも通ってしまうため、versionCode で判定

versionCode で判定

---

.github/workflows/build.yml

> [!IMPORTANT]
> マージせず放置してください
---
---
タイトルの通り

LINE の versionName を修正

---

.github/workflows/build.yml

---
#149 の修正
５桁目までがLINEのバージョン
14.9.1: 14091
多分

versionName を修正

---

README.md

Actions から LSPatch する方法を追加

---

app/build.gradle
app/src/main/java/io/github/chipppppppppp/lime/hooks/Constants.java

　クラス名をline 14.16.0に更新

---

app/src/main/java/io/github/chipppppppppp/lime/hooks/RemoveAds.java

adClassNames を自動で検知して追加するように変更
バージョンアップで都度adClassNameが変わるため
---

adClassNames を自動で検知して追加するように変更

---

app/src/main/java/io/github/chipppppppppp/lime/hooks/CheckHookTargetVersion.java

バージョンコードを取得するように訂正

---

app/src/main/java/io/github/chipppppppppp/lime/LimeOptions.java
app/src/main/java/io/github/chipppppppppp/lime/Main.java
app/src/main/java/io/github/chipppppppppp/lime/hooks/Archived.java
app/src/main/java/io/github/chipppppppppp/lime/hooks/Ringtone.java
app/src/main/res/values-ja/strings.xml
app/src/main/res/values/strings.xml

LSPatch 時の着信音が鳴らない問題を修正

---

app/build.gradle
app/src/main/java/io/github/chipppppppppp/lime/LimeOptions.java
app/src/main/java/io/github/chipppppppppp/lime/hooks/RemoveFlexibleContents.java
app/src/main/res/values-ja/strings.xml
app/src/main/res/values/strings.xml

Update RemoveFlexibleContents.java オプションの追加

---

.github/CODEOWNERS

CODEOWNERS を削除

---

app/src/main/AndroidManifest.xml

---
```XML
<category android:name="de.robv.android.xposed.category.MODULE_SETTINGS" />
```
を追加

Fix MainActivity category

---

.github/workflows/build.yml
README.md

README を更新

---

.github/workflows/build.yml

Actions の実行条件を修正

---

.github/workflows/build.yml

tags-ignore を削除

---

app/src/main/java/io/github/chipppppppppp/lime/hooks/RedirectWebView.java

---
<https://developers.line.biz/ja/docs/line-login/using-line-url-scheme/>

URLスキームを追加

---

app/src/main/java/io/github/chipppppppppp/lime/hooks/SendMuteMessage.java

常にミュートメッセージ　機能に伴うバグの修正(ラベルリソースの置換)

---

README.md

---
LsPosedは既に開発が終了されており、OS14 以降では、正常にモジュールが追加できない。
そのため、フォークで開発がすすめられているJingMatrix版LsPosedを記載した。

JingMatrix版LsPosedの記載

---

app/build.gradle
app/src/main/java/io/github/chipppppppppp/lime/Main.java
app/src/main/java/io/github/chipppppppppp/lime/hooks/RedirectWebView.java
gradle.properties

Use AndroidX 
